### PR TITLE
Add go-micro flag

### PR DESCRIPTION
**Pull request by Taik**
This PR adds support for generating [Micro-specific](https://micro.mu/blog/2016/03/28/go-micro.html#3-generate-the-api-interface) proto bindings.

The forked micro/protobuf isn't implemented as an independent protobuf plugin, but rather is forked off the original golang/protobuf with built-in support for `plugins=micro` flag.

### CODE REVIEW

**Comment by peter-edge** [comment]
I don't think this will work if both grpc and go-micro are set

**Comment by Taik** [comment]
Hey thanks for getting back; from the docs it seems like multiple plugins is supported via `plugins=plugin1+plugin2`. I'll send the changes in a bit.

**Comment by peter-edge** [comment]
Ok sounds good. You'll also have to add everything to vendor :)

**Comment by chrrrles** [comment]
+1 for this.  We are currently using this pull request in a custom protoeasy package (`sed` to the rescue...).  It will be great seeing this (with multiple plugin support) integrated into the main pedge.io tree.

**Comment by peter-edge** [comment]
I'm happy to get this in, but everything needs to be in vendor, etc etc.

**Comment by peter-edge** [comment]
Nothing was added to vendor, etc etc. Closing this for now.

**Pull request closed without merging**
