### PR TITLE
Add swagger support 

### PR DESCRIPTION
**Pull request by suusan2go**
Thanks for this nice tool !

I want to generate  swagger definitions supported by `grpc-gateway`( using `protoc-gen-swagger`).
But official docker image `quay.io/pedge/protoeasy` dose not include `protoc-gen-swagger`.
So I added to `Makefile`,  ran `make vendor`,  and add `extra-plugin-flag` to `examples` for tests.

Please let me know if there are other necessary steps.

### CODE REVIEW

**Comment by peter-edge** [comment]
If I were to include this, I'd want it to be officially supported as an option as opposed to using `--extra-plugin-flag`, and that is expanding the scope of this.

Another option: Why not just have your own docker image using this Dockerfile:

```
FROM quay.io/pedge/protoeasy

RUN go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
```

**Comment by peter-edge** [comment]
Hey @suusan2go closing this for now, feel free to reopen!

**Comment by suusan2go** [comment]
@peter-edge I'm sorry for late reply. Actually I already made my own docker image,  but I'd want it to be officially supported because grpc-gateway officially supports generating swagger definitions.
Something like `--grpc-gateway-swager` option is suitable ? If it's ok,  I'll make another pull request.

**Comment by peter-edge** [comment]
Sure, go for it.

**Pull request closed without merging**
